version: '3.8'
services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - 9000
    volumes:
      - '/data/coolify/applications/a0kgwssg8o4gs08s4s4s0wkg/data/var/www/html:/var/www/html'
    restart: always

  web:
    image: 'nginx:stable-alpine'
    volumes:
      - '/data/coolify/applications/a0kgwssg8o4gs08s4s4s0wkg/data/var/www/html:/var/www/html'
      - './nginx.conf:/etc/nginx/conf.d/default.conf'
      - '/data/certs/nepbelgium_be:/etc/nginx/certs:ro'
    ports:
      - '3000:80'
      - '3443:443'
    depends_on:
      - php
    restart: always